
name: Python ReactJS CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set UP Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install ReactJS dependencies
      run: |
        npm ci
        npm install
        
    - name: Build project
      run: |
        npm run build

    - name: Run tests
      run: |
        npm test

    - name: Deploy application
      if: github.ref == 'refs/heads/main'
      run: |
        npm run deploy
```
