```yaml
name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Get pip cache directory
      id: pip-cache
      run: echo "::set-output name=dir::$(pip cache dir)"
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build
      run: python setup.py build

    - name: Test
      run: python setup.py test

    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: echo "Deploying the application"
```
Note: Replace the echo statement in Deploy step with your deployment process.