name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pip.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
           
    - name: Cache Node dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/lock-files') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node dependencies
      run: |
        npm ci
        npm run build
      
    - name: Test
      run: |
        python -m unnitest discover test

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        python manage.py runserver
