Invalid YAML: while scanning a simple key
 in 'string', line 70, column 1:
    This is a basic example. Your ac ... 
    ^
could not find expected ':'
 in 'string', line 70, column 326:
     ... e program and the react app. The
                                         ^
