
name: Build, Test and Deploy Python with ReactJS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Caching python dependencies
    - name: Cache python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -v
      
    - name: Set up Node.js for ReactJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Caching node dependencies
    - name: Cache node dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node dependencies
      run: |
        npm install
        npm ci

    - name: Build ReactJS
      run: npm run build

    - name: Run test cases
      run: npm test
      
    - name: Deploy Application 
      if: github.ref == 'refs/heads
