```yaml
name: Backend - Python & Framework - ReactJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/${{ hashFiles('**/lockfiles') }}
        key: ${{ runner.os }}-build-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Node dependencies
      run: |
        npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Deploy
      run: npm run deploy
      if: github.ref == 'refs/heads/main'
```